openapi: 3.0.0
info:
  version: '1'
  title: 'CarriersRates'
  description: Get carrier shipping methods with price. In this version was added transitInTime
servers:
  - url: http://carriers/openapi/CarriersRates/v1
  - url: http://localhost:8080/openapi/CarriersRates/v1
tags:
  - name: Rates
  - name: TransitInTime
paths:
  "/rates":
    post:
      tags:
        - Rates
      summary: "Get carrier rates"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RatesPostRequest'
      responses:
        "200":
          description: "Order successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatesResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
  "/transitInTime":
    post:
      tags:
        - TransitInTime
      summary: "Get carrier arrive date"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostTransitInTimeRequest'
      responses:
        "200":
          description: "Order successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransitInTimeResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
components:
  schemas:
    # Basic results components
    ErrorResult:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - LOGGER_MESSAGE
          description: >
            You can expose this enum for all your errors
            UNDEFINED - Any undefined message type
            LOGGER_MESSAGE - Same as undefined
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResult:
      allOf:
        - $ref: '#/components/schemas/ErrorResult'
      type: object
      properties:
        data:
          type: object

    ## One resource result
    RatesResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Rates'

    TransitInTimeResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TransitInTimeData'
    PostTransitInTimeRequest:
      type: object
      required:
        - carrier
        - zipFrom
        - zipTo
        - weight
        - weightUnitOfMeasurement
        - width
        - length
        - height
        - shippingMethodName
      properties:
        carrier:
          type: string
          enum:
            - USPS
            - FedEx
            - UPS
        zipFrom:
          type: string
          example: "91601"
        zipTo:
          type: string
          example: "91730"
        weight:
          type: number
          example: 80.5
        weightUnitOfMeasurement:
          type: string
          enum:
            - pound
            - ounce
        width:
          type: number
          description: width in inches
        length:
          type: number
          description: length in inches
        height:
          type: number
          description: height in inches
        sendDate:
          type: string
          example: "2023-11-15"
          description: By default now UTC
        shippingMethodName:
          type: string
          description: Allowed methods
          enum:
            # UPS
            - UPS Ground
            # USPS
            - USPS Ground Advantage
            - Priority Mail
            # Fedex
            - GROUND_HOME_DELIVERY
            - FIRST_OVERNIGHT
            - PRIORITY_OVERNIGHT
            - STANDARD_OVERNIGHT
            - FEDEX_2_DAY
            - FEDEX_EXPRESS_SAVER
    ## Body for post request
    RatesPostRequest:
      type: object
      required:
        - carrier
      properties:
        carrier:
          type: string
          enum:
            - USPS
            - FedEx
            - UPS
        zipFrom:
          type: string
          example: "91601"
        zipTo:
          type: string
          example: "91730"
        weight:
          type: number
          example: 80.5
        weightUnitOfMeasurement:
          type: string
          enum:
            - pound
            - ounce
        width:
          type: number
          description: width in inches
        length:
          type: number
          description: length in inches
        height:
          type: number
          description: height in inches
        sendDateTime:
          type: string
          example: "2023-11-15 12:00:00"
    ## Resource object
    Rates:
      type: object
      properties:
        rates:
          type: array
          description: List of rates
          items:
            $ref: '#/components/schemas/Rate'
    TransitInTimeData:
      type: array
      items:
        $ref: '#/components/schemas/TransitInTimeItem'
    TransitInTimeItem:
      type: object
      required:
        - shippingMethodName
        - shippingArriveDate
        - shippingSendDate
      properties:
        shippingMethodName:
          type: string
          description: Allowed methods
          enum:
            # UPS
            - UPS Ground
            # USPS
            - USPS Ground Advantage
            - Priority Mail
            # Fedex
            - GROUND_HOME_DELIVERY
            - FIRST_OVERNIGHT
            - PRIORITY_OVERNIGHT
            - STANDARD_OVERNIGHT
            - FEDEX_2_DAY
            - FEDEX_EXPRESS_SAVER
        shippingArriveDate:
          type: string
          example: '2023-11-19 21:00:00'
        shippingSendDate:
          type: string
          example: '2023-11-16 21:00:00'
    Rate:
      type: object
      properties:
        shippingMethodName:
          type: string
          enum:
            - UPS Ground
            - USPS Ground Advantage
            - First-Class Package Service
            - Priority Mail Cubic
            - Parcel Select Ground
            - Priority Mail
            - Priority Mail Flat Rate Envelope
            - Priority Mail Legal Flat Rate Envelope
            - Priority Mail Flat Rate Padded Envelope
            - FEDEX_INTERNATIONAL_PRIORITY_EXPRESS
            - INTERNATIONAL_FIRST
            - FEDEX_INTERNATIONAL_PRIORITY
            - INTERNATIONAL_ECONOMY
            - FEDEX_GROUND
            - FEDEX_CARGO_MAIL
            - FEDEX_CARGO_INTERNATIONAL_PREMIUM
            - FIRST_OVERNIGHT
            - FIRST_OVERNIGHT_FREIGHT
            - FEDEX_1_DAY_FREIGHT
            - FEDEX_2_DAY_FREIGHT
            - FEDEX_3_DAY_FREIGHT
            - INTERNATIONAL_PRIORITY_FREIGHT
            - INTERNATIONAL_ECONOMY_FREIGHT
            - FEDEX_CARGO_AIRPORT_TO_AIRPORT
            - INTERNATIONAL_PRIORITY_DISTRIBUTION
            - FEDEX_IP_DIRECT_DISTRIBUTION_FREIGHT
            - INTL_GROUND_DISTRIBUTION
            - GROUND_HOME_DELIVERY
            - SMART_POST
            - PRIORITY_OVERNIGHT
            - STANDARD_OVERNIGHT
            - FEDEX_2_DAY
            - FEDEX_2_DAY_AM
            - FEDEX_EXPRESS_SAVER
            - SAME_DAY
            - SAME_DAY_CITY
            - FEDEX_FIRST_FREIGHT
        shippingContainerName:
          type: string
          nullable: true
          enum:
            - One Rate Box
            - One Rate Small Box
            - One Rate Envelope
        totalPrice:
          type: number
          example: 7.85
        shippingArriveDate:
          type: string
          nullable: true
          example: '2023-11-19 21:00:00'
        shippingSendDate:
          type: string
          nullable: true
          example: '2023-11-16 21:00:00'