openapi: 3.0.0
info:
  version: "1"
  title: "CrmDealCreator"
  description: API to create dropships and pickups in CRM
servers:
  - url: http://server-host/openapi/CrmDealCreator/v1
paths:
  "/deals":
    post:
      summary: "Make an deal"
      description: ""
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DealPostRequest'
      responses:
        "200":
          description: "Order successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DealPostResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
components:
  schemas:
    # Basic results components
    ErrorResult:
      type: object
      properties:
        messages:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - LOGGER_MESSAGE
          description: >
            You can expose this enum for all your errors
            UNDEFINED - Any undefined message type
            LOGGER_MESSAGE - Same as undefined 
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResult:
      allOf:
        - $ref: '#/components/schemas/ErrorResult'
      type: object
      properties:
        data:
          type: object
          nullable: true

    ## One resource result
    DealPostResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          nullable: true
          allOf:
            - $ref: '#/components/schemas/Deal'

    ## Body for post request
    DealPostRequest:
      type: object
      required:
        - requiredField
      properties:
        requiredField:
          type: string
          description: required
        optionalField:
          type: string
          nullable: true
          description: optional

    ## Deal object
    Deal:
      type: object
      properties:
        id:
          type: string
          description: Unique identificator of order (generated by server).
          example: "AP7734"
        requiredField:
          type: string
          description: Order number received from supplier
        optionalField:
          type: string
          nullable: true
          example: null
        objectField:
          $ref: '#/components/schemas/NestedObject'
        arrayField:
          type: array
          description: List of ordered products
          items:
            $ref: '#/components/schemas/NestedObject'
    
    NestedObject:
      type: object
      properties:
        name:
          type: string
          description: Some name
          example: "name"