openapi: 3.0.0
info:
  version: "1"
  title: "CrmDealCreator"
  description: API to create dropships and pickups in CRM
servers:
  - url: http://rollun-crm/openapi/CrmDealCreator/v1
tags:
  - name: Deals
paths:
  "/deals/dropships":
    post:
      tags:
        - Deals
      operationId: createDropshipDeal
      summary: "Make an deal"
      description: "Create dropship deal"
      requestBody:
        description: "Dropship deal data"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DropshipDealPostRequest'
      responses:
        "200":
          description: "Deal successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DealPostResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
  "/deals/pickups":
    post:
      tags:
        - Deals
      operationId: createPickupDeal
      summary: "Make an deal"
      description: "Create pickup deal"
      requestBody:
        description: "Pickup deal data"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PickupDealPostRequest'
      responses:
        "200":
          description: "Deal successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DealPostResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
components:
  schemas:
    # Basic results components
    ErrorResult:
      type: object
      properties:
        messages:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - LOGGER_MESSAGE
          description: >
            You can expose this enum for all your errors
            UNDEFINED - Any undefined message type
            LOGGER_MESSAGE - Same as undefined
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResult:
      allOf:
        - $ref: '#/components/schemas/ErrorResult'
      type: object
      properties:
        data:
          type: object
          nullable: true

    ## One resource result
    DealPostResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          nullable: true
          allOf:
            - $ref: '#/components/schemas/Deal'

    ## Body for post request
    DropshipDealPostRequest:
      allOf:
        - $ref: '#/components/schemas/AbstractDealPostRequest'
      type: object

    PickupDealPostRequest:
      allOf:
        - $ref: '#/components/schemas/AbstractDealPostRequest'
      type: object
      required:
        - labelProvider
      properties:
        labelProvider:
          type: string
          description: Only for pickup orders
          enum:
            - Rollun
            - Amazon

    AbstractDealPostRequest:
      type: object
      required:
        - mpName
        - mpOrderNumber
        - srName
        - srShipMethod
        - carrier
        - sender
        - relatedOrder
        - positions
      properties:
        mpName:
          type: string
        mpOrderNumber:
          type: string
        srName:
          type: string
        srShipMethod:
          type: string
        enterTracknumber:
          type: string
          default: "products in order"
        carrier:
          type: string
        sender:
          type: string
        relatedOrder:
          type: string
        positions:
          type: array
          items:
            $ref: '#/components/schemas/DealPosition'

    DealPosition:
      type: object
      required:
        - rid
        - dealId
      properties:
        rid:
          type: string
        dealId:
          type: string
        quantity:
          type: integer
          default: 1
          minimum: 1
        cost:
          type: number
          format: double
          default: 0
          minimum: 0



    ## Deal object
    Deal:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: Unique identificator of deal (generated by server).
          example: "12345"