openapi: 3.0.0
info:
  version: "1"
  title: "CrmDealCreator"
  description: API to create dropships and pickups in CRM
servers:
  - url: http://server-host/openapi/CrmDealCreator/v1
paths:
  "/deals/dropships":
    post:
      operationId: createDropshipDeal
      summary: "Make an deal"
      description: ""
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DropshipDealPostRequest'
      responses:
        "200":
          description: "Order successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DealPostResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
  "/deals/pickups":
    post:
      operationId: createPickupDeal
      summary: "Make an deal"
      description: ""
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PickupDealPostRequest'
      responses:
        "200":
          description: "Order successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DealPostResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
components:
  schemas:
    # Basic results components
    ErrorResult:
      type: object
      properties:
        messages:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - LOGGER_MESSAGE
          description: >
            You can expose this enum for all your errors
            UNDEFINED - Any undefined message type
            LOGGER_MESSAGE - Same as undefined 
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResult:
      allOf:
        - $ref: '#/components/schemas/ErrorResult'
      type: object
      properties:
        data:
          type: object
          nullable: true

    ## One resource result
    DealPostResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          nullable: true
          allOf:
            - $ref: '#/components/schemas/Deal'

    ## Body for post request
    DropshipDealPostRequest:
      allOf:
        - $ref: '#/components/schemas/AbstractDealPostRequest'
      type: object
    
    PickupDealPostRequest:
      allOf:
        - $ref: '#/components/schemas/AbstractDealPostRequest'
      type: object
      required: 
        - labelProvider
      properties:
        labelProvider:
          type: string
          nullable: true
          description: Only for pickup orders
        
      
    AbstractDealPostRequest:
      type: object
      required:
        - mpName
        - mpOrderNumber
        - srShipMethod
        - enterTracknumber
        - srName
        - carrier
        - relatedOrder
        - owner
        - sender
        - positions
      properties:
        mpName:
          type: string
        mpOrderNumber:
          type: string
        srShipMethod:
          type: string
        enterTracknumber:
          type: string
          default: "products in order"
        srName:
          type: string
        carrier:
          type: string
        relatedOrder:
          type: string
        owner:
          type: string
          nullable: true
        sender:
          type: string
        positions:
          type: array
          items:
            $ref: '#/components/schemas/DealPosition'
    
    DealPosition:
      type: object
      properties:
        id:
          type: string
        dealId:
          type: string
        offerId:
          type: string
        cost:
          type: number
          format: double
          default: 0
          minimum: 0
        quantity:
          type: integer
          minimum: 0
        article:
          type: string
        name:
          type: string
        

    ## Deal object
    Deal:
      type: object
      properties:
        id:
          type: string
          description: Unique identificator of deal (generated by server).
          example: "12345"