openapi: 3.0.0
info:
  version: "1"
  title: "EbayProductInfo"
  description: Get product info for ebay
servers:
  - url: http://catalog/openapi/EbayProductInfo/v1
tags:
  - name: Product

paths:
  "/specs/{marketplace}/{rid}":
    get:
      tags:
        - Product
      summary: "Get specifications info by rid for specific marketplace"
      parameters:
        - name: marketplace
          in: path
          required: true
          description: '' # todo
          schema:
            type: string
            enum:
              - "Plaisir"
              - "Rollun"
              - "Any"
            default: "Any"
        - name: rid
          in: path
          required: true
          schema:
            type: string
        - name: recalculate
          in: query
          required: false
          description: If true - value will be recalculated from scratch, bypassing cache
          schema:
            type: boolean
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpecsResponse"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        messages:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - INVALID_RESPONSE
            - NO_STRATEGY
            - MISSING_DATA
          description: >
            UNDEFINED - Any undefined message type
            INVALID_RESPONSE - A message generated by the client stating that the response could not be decoded
            NO_STRATEGY - There is no strategy to compute requested value
            MISSING_DATA - Some crucial data is missing to generate valid response
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResponse:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      type: object
      properties:
        data:
          type: object
    SpecsResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
      properties:
        data:
          $ref: '#/components/schemas/Specs'

    ## Resource object
    Specs:
      type: object
      required:
        - Brand
        - Manufacturer Part Number
        - Quantity
        - Aspect Ratio
        - Section Width
        - Wheel Diameter
      properties:
        Brand:
          type: string
          nullable: false
          default: "Unbranded"
        Manufacturer Part Number:
          type: string
          nullable: false
          default: "Does Not Apply"
        Quantity:
          type: integer
          nullable: false
          default: 1
        Aspect Ratio:
          type: string
          nullable: false
          default: "Unknown"
        Section Width:
          type: string
          nullable: false
          default: "Unknown"
        Wheel Diameter:
          type: string
          nullable: false
          default: "Unknown"
        Model:
          type: string
          nullable: true
        Machine Type:
          type: string
          nullable: true
        Placement on Vehicle:
          type: string
          nullable: true
        Load Index:
          type: string
          nullable: true
        Speed Index:
          type: string
          nullable: true
        Unit Type:
          type: string
          nullable: true
        Unit Quantity:
          type: integer
          nullable: true
          default: 1
