openapi: 3.0.0
info:
  version: "1"
  title: "LabelsAmazon"
  description: Manifest description
servers:
  - url: http://amz-orders-ngx/openapi/LabelsAmazon/v1
  - url: http://host.docker.internal:8408/openapi/LabelsAmazon/v1
tags:
  - name: Labels
paths:
  "/labels":
    post:
      tags:
        - Labels
      summary: "Make an label"
      description: ""
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelPostRequest'
      responses:
        "200":
          description: "Label successfully created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelResult'
        "500":
          description: 'Some internal error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
  "/methods":
    post:
      tags:
        - Methods
      summary: 'Getting Shipping Methods'
      description: 'Returns shipping methods by Amazon with prices, sender, and delivery time.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelAmazonPostRequest'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelShippingServiceList'
        '400':
          description: 'Invalid input data'
components:
  schemas:
    LabelShippingServiceList:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/LabelShippingServiceListItem'
    LabelShippingServiceListItem:
      type: object
      required:
        - ShippingServiceName
        - CarrierName
      properties:
        ShippingServiceName:
          type: string
          description: "UPS Next Day Air Saver®"
        CarrierName:
          type: string
          example: "UPS"
        ShippingServiceId:
          type: string
          example: "AAAAAAAAAAAqnDNfzNUo1n6aEt88FZsDjQAAAAAAAAAh3Ewby/F4ajoYUgp/71GgjGcDSToMKTCeu+BOItBLGK9C3BcLwZ3swXfFWephs6kJnSfr4inJbd00c0RYmqDX+59LebA+Ita/yNIm0z0AhI7qY4KUFTlN8mOVilhSmzV2HtU/cg1Gp1bwvuk3kFRaEm63QTJa/1imCS1AzLsXNq0ApkqWgoaWayLVs+Y="
        ShippingServiceOfferId:
          type: string
          example: "UPS_PTP_NEXT_DAY_AIR_SAVER"
        ShipDate:
          type: string
          example: "2023-08-02T15:20:08Z"
        EarliestEstimatedDeliveryDate:
          type: string
          example: "2023-08-04T06:00:00Z"
        LatestEstimatedDeliveryDate:
          type: string
          example: "2023-08-04T06:00:00Z"
        Rate:
          type: object
          properties:
            CurrencyCode:
              type: string
              example: "USD"
            Amount:
              type: number
              example: 10.2
        ShippingServiceOptions:
          type: object
          properties:
            DeliveryExperience:
              type: string
              example: "DeliveryConfirmationWithAdultSignature"
            CarrierWillPickUp:
              type: boolean
              example: false
            LabelFormat:
              type: string
              nullable: true
              example: ''
        AvailableLabelFormats:
          type: array
          items:
            $ref: '#/components/schemas/AvailableLabelFormatsItems'
        AvailableFormatOptionsForLabel:
          type: array
          items:
            $ref: '#/components/schemas/AvailableFormatOptionsForLabelItem'
    AvailableFormatOptionsForLabelItem:
      type: object
      properties:
        AvailableFormatOptionsForLabel:
          type: string
          example: 'ShippingServiceDefault'
    AvailableLabelFormatsItems:
      type: string
      example: 'ShippingServiceDefault'
    LabelAmazonPostRequest:
      type: object
      properties:
        orderId:
          type: string
          example: "114-5985888-9227450"
        sellerOrderId:
          type: string
          example: "510175"
        items:
          type: array
          items:
            $ref: '#/components/schemas/LineItems'
        sender:
          allOf:
            - $ref: '#/components/schemas/Customer'
          description: Sender of the shipment.
        weight:
          type: number
          example: 80.5
        width:
          type: number
          description: width in inches
          example: 12
        length:
          type: number
          description: length in inches
          example: 13.13
        height:
          type: number
          description: height in inches
          example: 0.13
        customId:
          type: string
          example: "510234"
        sendDate:
          type: string
          description: Sending date. When parcel will be send. Format - Y-m-d\TH:i:s in UTC
          example: "2024-05-31T12:12:12"
    # Basic results components
    ErrorResult:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      description: "Message field is not required"
    Message:
      type: object
      properties:
        level:
          type: string
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
        type:
          type: string
          enum:
            - UNDEFINED
            - WRONG_SHIPPING_TYPE
            - LOGGER_MESSAGE
          description: >
            You can expose this enum for all your errors
            UNDEFINED - Any undefined message type
            LOGGER_MESSAGE - Same as undefined
        text:
          type: string
          description: Message, that describes what went wrong
    SuccessResult:
      allOf:
        - $ref: '#/components/schemas/ErrorResult'
      type: object
      properties:
        data:
          type: object

    ## One resource result
    LabelResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Label'
    LineItems:
      type: object
      properties:
        OrderItemId:
          type: string
          example: "100046634443841"
        Quantity:
          type: number
          example: 1

    ## Body for post request
    LabelPostRequest:
      type: object
      required:
        - requiredField
      properties:
        orderId:
          type: string
          example: "114-5985888-9227450"
        sellerOrderId:
          type: string
          example: "510175"
        items:
          type: array
          items:
            $ref: '#/components/schemas/LineItems'
        sender:
          allOf:
            - $ref: '#/components/schemas/Customer'
          description: Sender of the shipment.
        shippingMethodName:
          type: string
          enum:
            - "First-Class Package Service"
            - "Priority Mail"
            - "Priority Mail Legal Flat Rate Envelope"
            - "Priority Mail Flat Rate Padded Envelope"
            - "Priority Mail Small Flat Rate Box"
            - "Priority Mail Medium Flat Rate Box"
            - "Priority Mail Large Flat Rate Box"
            - "Priority Mail Regional Rate Box A"
            - "Priority Mail Regional Rate Box B"
            - "Parcel Select"
            - "Parcel Select Ground"
            - "Priority Mail Flat Rate Envelope"
            - "Priority Mail Cubic"
            - "Priority Mail Large Flat Rate Board Game Box"
            - "Priority Mail Medium Flat Rate Box"
            - "Ground Advantage"
            - "Ground"
            - "Ground Saver"
        weight:
          description: Should be in LBS only
          type: number
          example: 80.5
        width:
          type: number
          description: width in inches
          example: 12
        length:
          type: number
          description: length in inches
          example: 10
        height:
          type: number
          description: height in inches
          example: 3
        customId:
          type: string
          example: "510234"


    ## Resource object
    Label:
      type: object
      properties:
        labelImage:
          type: string
          description: base64 encoded label image in pdf
        trackNumber:
          type: string
        totalPrice:
          type: number
          example: 7.85
    Customer:
      type: object
      required:
        - name
        - address
      properties:
        name:
          type: string
          description: Full name
          example: Shawn Weisweaver
        phone:
          type: string
          nullable: true
          description: Phone number to reach the person
          example: "415-123-4567"
        email:
          type: string
          nullable: true
          description: Email address to reach the person
          example: "test@mail.loc"
        address:
          $ref: "#/components/schemas/Address"
    Address:
      type: object
      required:
        - country
        - state
        - city
        - postalCode
        - address1
      properties:
        #        pickupAddress:
        #          type: string
        country:
          type: string
          description: "Country code"
        state:
          type: string
          description: US state code
          example: CA
        city:
          type: string
          description: Full city name
          example: San Francisco
        postalCode:
          type: string
          description: ZIP or postal code
          example: "94104"
        address1:
          type: string
          description: First line of the address
          example: "417 Montgomery St"