openapi: 3.0.0
paths:
  "/api/v1/secrets/{id}":
    get:
      operationId: SecretsController_getSecretById
      summary: Get secret by id (latest version)
      description: Get secret by id
      parameters:
      - name: id
        required: true
        in: path
        description: Secret ID
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SecretDto"
        '400':
          description: Invalid params
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/BadRequestDto"
        '404':
          description: ''
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/InternalServerErrorDto"
      tags:
      - Secrets
  "/api/v1/secrets/{id}/all-versions":
    get:
      operationId: SecretsController_getAllVersionsOfSecretById
      summary: Get all versions of secret by id
      description: Get all versions of secret by id
      parameters:
      - name: id
        required: true
        in: path
        description: Secret ID
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/SecretDto"
        '400':
          description: Invalid params
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/BadRequestDto"
        '404':
          description: ''
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/InternalServerErrorDto"
      tags:
      - Secrets
  "/api/v1/secrets":
    get:
      operationId: SecretsController_getAllSecrets
      summary: Get all secrets
      description: Get all secrets
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/SecretDto"
        '400':
          description: Invalid params
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/BadRequestDto"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/InternalServerErrorDto"
      tags:
      - Secrets
    post:
      operationId: SecretsController_createSecret
      summary: Create secret
      description: Create secret
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateSecretBody"
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SecretDto"
        '400':
          description: Invalid params
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/BadRequestDto"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/InternalServerErrorDto"
      tags:
      - Secrets
info:
  title: Rollun service manager
  description: Service for creating automation
  version: '1.0'
  contact: {}
tags: []
servers:
- url: http://secret-manager
components:
  schemas:
    BadRequestDto:
      type: object
      properties:
        statusCode:
          type: number
          enum:
          - 400
        error:
          type: string
          enum:
          - Bad Request
      required:
      - statusCode
      - error
    InternalServerErrorDto:
      type: object
      properties:
        statusCode:
          type: number
          enum:
          - 500
        message:
          type: string
          enum:
          - Internal Server Error
      required:
      - statusCode
      - message
    SecretDto:
      type: object
      properties:
        id:
          type: string
          description: Secret ID
        value:
          type: string
          description: Secret value
        version:
          type: string
          description: Secret version
        createdAt:
          type: string
          description: Secret created at
      required:
      - id
      - value
      - version
      - createdAt
    CreateSecretBody:
      type: object
      properties:
        id:
          type: string
          description: Secret ID
        value:
          type: string
          description: Secret value
      required:
      - id
      - value
