openapi: 3.0.0
info:
  version: '1'
  title: ShippingMethods
  description: 'Service howtobuy. The service provides methods for obtaining possible delivery methods according to the specified parameters'
externalDocs:
  url: https://github.com/rollun-com/service-howtobay
servers:
  - url: http://carriers/openapi/ShippingMethods/v1
tags:
  - name: Shipping
    description: 'Everything about shipping methods.'
paths:
  /shipping:
    post:
      tags:
        - Shipping
      summary: 'Getting Shipping Methods'
      description: 'Returns possible shipping methods with prices, sender, and delivery time.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShippingInfo'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetShippingBody'
        '400':
          description: 'Invalid input data'
components:
  schemas:
    ShippingInfo:
      type: object
      required:
        - zipTo
        - weight
        - width
        - length
        - height
      properties:
        zipTo:
          type: string
          example: "78228"
        weight:
          type: number
          example: 1.0
        width:
          type: number
          example: 2.0
        length:
          type: number
          example: 3.5
        height:
          type: number
          example: 4.0
        senders:
          type: array
          nullable: true
          items:
            type: string
            example: pu_fast_ds
        isDangerous:
          description: 'Whether the package contains hazardous materials. It is necessary to determine the possibility of sending by air.'
          type: boolean
          example: false
          nullable: true
        isTire:
          description: 'Flag affects the validator'
          type: boolean
          example: false
          nullable: true
        # RM
        rmCategory:
          description: 'Category for RM, affects the price'
          type: string
          example: 'Filters'
          nullable: true
        rmIsKit:
          description: 'IsKit for RM, affects the price'
          type: boolean
          example: false
          nullable: true
        rmFee:
          description: 'A fee of RM, affects the price'
          type: number
          example: 10.2
          nullable: true
        rmIsOversize:
          description: 'Flag IsOversize for RM, affects the price'
          type: string
          enum:
            - Y
            - N
          example: Y
          nullable: true
        # AU
        auIsFirstClass:
          description: 'If possible, then send a parcel First Class'
          type: string
          enum:
            - Y
            - N
          example: Y
          nullable: true
        auFlatRateGroup:
          description: 'Flag affects the price'
          type: string
          example: ATV25
          nullable: true
        auLargePackageSurcharge:
          description: 'Flag affects the price'
          type: number
          example: 10.2
          nullable: true
        # TR
        trWidth:
          description: 'A flag that matches the width, but may be different. Affects the price'
          type: number
          example: 3.1
          nullable: true
        trHeight:
          description: 'A flag that matches the height, but may be different. Affects the price'
          type: number
          example: 3.1
          nullable: true
        trLength:
          description: 'A flag that matches the length, but may be different. Affects the price'
          type: number
          example: 3.1
          nullable: true
        trSubcategory:
          description: 'Flag affects the price'
          type: string
          example: Offroad Tires
          nullable: true
        trNewCategory:
          description: 'Flag affects the price'
          type: string
          example: TIRES
          nullable: true
        trNewSubCategory:
          description: 'Flag affects the price'
          type: string
          example: KITS
          nullable: true
        trFee:
          description: 'Flag affects the price'
          type: number
          example: 1.3
          nullable: true
        trIsOversize:
          description: 'Flag affects the price'
          type: string
          nullable: true
          enum:
            - '1'
            - '2'
            - '3'
          example: '1'
    ShippingResponse:
      type: object
      required:
        - deliverySender
        - shippingMethodId
        - shippingMethodName
        - trackNumberDate
        - shippingSendDate
        - shippingArriveDate
        - carrier
        - cost
      properties:

        deliverySender:
          type: string
          example: 'wps_ds'
        shippingMethodId:
          type: string
          example: 'PU-PickUp-Usps-PM-FR-BgBox'
        shippingMethodName:
          type: string
          example: 'Priority Mail Large Flat Rate Board Game Box'
        cost:
          type: number
          example: 5.84
          nullable: true
        trackNumberDate:
          type: string
          example: '30.01.2020 09:00:00'
        shippingArriveDate:
          nullable: true
          type: string
          example: '03.02.2020 09:00:00'
        shippingSendDate:
          type: string
          example: '03.02.2020 09:00:00'
        carrier:
          type: string
          enum:
            - Usps
            - Fedex
          example: Fedex
          nullable: true
      xml:
        name: Shipping
    GetShippingBody:
      type: object
      properties:
        data:
          type: array
          description: 'Found delivery methods'
          items:
            $ref: '#/components/schemas/ShippingResponse'
        messages:
          type: array
          description: 'Collection of messages. There may be errors, notes and more.'
          items:
            $ref: '#/components/schemas/Message'
      xml:
        name: GetShippingBody
    Message:
      type: object
      required:
        - level
        - message
      properties:
        level:
          type: string
          description: 'Message level (type)'
          example: 'error'
        message:
          type: string
          description: 'Message text'
          example: 'DataStore Test unavailable.'
      xml:
        name: Message