openapi: 3.0.0
info:
  version: "1"
  title: "ShippingMethods"
  description: Get carrier shipping methods with price
servers:
  - url: http://carriers:81/openapi/ShippingMethods/v1
tags:
  - name: Amazon
paths:
  "/amazon":
    post:
      tags:
        - Amazon
      summary: 'Getting Shipping Methods'
      description: 'Returns shipping methods by Amazon with prices, sender, and delivery time.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelPostRequest'
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelShippingServiceList'
        '400':
          description: 'Invalid input data'
components:
  schemas:
    LabelShippingServiceList:
      type: array
      items:
        $ref: '#/components/schemas/LabelShippingServiceListItem'
    Customer:
      type: object
      required:
        - name
        - address
      properties:
        name:
          type: string
          description: Full name
          example: Shawn Weisweaver
        phone:
          type: string
          nullable: true
          description: Phone number to reach the person
          example: "415-123-4567"
        email:
          type: string
          nullable: true
          description: Email address to reach the person
          example: "test@mail.loc"
        address:
          $ref: "#/components/schemas/Address"
    Address:
      type: object
      required:
        - country
        - state
        - city
        - postalCode
        - address1
      properties:
        country:
          type: string
          description: "Country code"
        state:
          type: string
          description: US state code
          example: CA
        city:
          type: string
          description: Full city name
          example: San Francisco
        postalCode:
          type: string
          description: ZIP or postal code
          example: "94104"
        address1:
          type: string
          description: First line of the address
          example: "417 Montgomery St"
    LabelShippingServiceListItem:
      type: object
      required:
        - ShippingServiceName
        - CarrierName
      properties:
        ShippingServiceName:
          type: string
          description: "UPS Next Day Air Saver®"
        CarrierName:
          type: string
          example: "UPS"
        ShippingServiceId:
          type: string
          example: "AAAAAAAAAAAqnDNfzNUo1n6aEt88FZsDjQAAAAAAAAAh3Ewby/F4ajoYUgp/71GgjGcDSToMKTCeu+BOItBLGK9C3BcLwZ3swXfFWephs6kJnSfr4inJbd00c0RYmqDX+59LebA+Ita/yNIm0z0AhI7qY4KUFTlN8mOVilhSmzV2HtU/cg1Gp1bwvuk3kFRaEm63QTJa/1imCS1AzLsXNq0ApkqWgoaWayLVs+Y="
        ShippingServiceOfferId:
          type: string
          example: "UPS_PTP_NEXT_DAY_AIR_SAVER"
        ShipDate:
          type: string
          example: "2023-08-02T15:20:08Z"
        EarliestEstimatedDeliveryDate:
          type: string
          example: "2023-08-04T06:00:00Z"
        LatestEstimatedDeliveryDate:
          type: string
          example: "2023-08-04T06:00:00Z"
        Rate:
          type: object
          properties:
            CurrencyCode:
              type: string
              example: "USD"
            Amount:
              type: number
              example: 10.2
        ShippingServiceOptions:
          type: object
          properties:
            DeliveryExperience:
              type: string
              example: "DeliveryConfirmationWithAdultSignature"
            CarrierWillPickUp:
              type: boolean
              example: false
            LabelFormat:
              type: string
              example: ''
        AvailableLabelFormats:
          type: array
          items:
            $ref: '#/components/schemas/AvailableLabelFormatsItems'
        AvailableFormatOptionsForLabel:
          type: array
          items:
            $ref: '#/components/schemas/AvailableFormatOptionsForLabelItem'
    AvailableFormatOptionsForLabelItem:
      type: object
      properties:
        AvailableFormatOptionsForLabel:
          type: string
          example: 'ShippingServiceDefault'
    AvailableLabelFormatsItems:
      type: string
      example: 'ShippingServiceDefault'
    LineItems:
      type: object
      properties:
        OrderItemId:
          type: string
        Quantity:
          type: number
    LabelPostRequest:
      type: object
      properties:
        pickupAddress:
          type: string
        orderId:
          type: string
        sellerOrderId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/LineItems'
        sender:
          allOf:
            - $ref: '#/components/schemas/Customer'
          description: Sender of the shipment.
        weight:
          type: number
          example: 80.5
        width:
          type: number
          description: width in inches
        length:
          type: number
          description: length in inches
        height:
          type: number
          description: height in inches
        customId:
          type: string